apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: http-deployment
spec:
  selector:
    matchLabels:
      app: http
  replicas: 1
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
      - name: http
        image: httpd
        ports:
        - containerPort: 80
